/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yl_ndkdemo_MainActivity */

#ifndef _Included_com_seedling_helloc_MainActivity
#define _Included_com_seedling_helloc_MainActivity

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seedling_helloc_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_seedling_helloc_MainActivity_hello
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
